# The Site Configuration

# The language of the webpage › http://www.lingoes.net/en/translator/langcode.htm
lang: en

# Change to your timezone › https://kevinnovak.github.io/Time-Zone-Picker
timezone:

title: Jarno van den Brink # the main title

tagline: >- # shown on the home page hero
  Security researcher and red team operator working on Windows internals, exploitation
  and malware development. Using the Windows API for things it was not built for.

description: >- # used by seo meta, link previews and the atom feed
  Security researcher and red teamer, blog on Windows internals,
  exploitation and malware development.

# Fill in the protocol & hostname for your site.
# e.g. 'https://username.github.io', note that it does not end with a '/'.
url: "https://jarnovdbrink.nl"

github:
  username: jarnovandenbrink

twitter:
  username: v0nzyy

social:
  name: Jarno van den Brink
  email: contact[at]jarnovdbrink.nl
  links:
    - https://twitter.com/
    - https://github.com/jarnovandenbrink
    - https://www.linkedin.com/in/jarno-b-a30ab41a2/

# The base URL of your site
baseurl: ""

plugins:
  - jekyll-feed

permalink: /posts/:title/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: false

sass:
  style: compressed

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - package*.json
